### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by ashawkey** [ashawkey/stable-dreamfusion#1]
"a high quality photo of a pineapple"

https://user-images.githubusercontent.com/25863658/194284983-623a4ade-0029-490e-b038-c7dfa83bb405.mp4

**Comment by ashawkey** [comment]
Failure cases: 

* A DSLR photo of a squirrel

https://user-images.githubusercontent.com/25863658/194286147-b38e7692-fa32-4936-846b-dd65a6e74111.mp4

**Comment by settinghead** [comment]
I tried DSLR photos of a panda, got a similar failed result. Curious: any guess why it failed?

**Comment by pablo-mayrgundter** [comment]
Maybe it's because small prey animals have adapted shape and color patterns to make it difficult to guess their true orientation and so which direction they're scurry or hop away.

**Comment by bitRAKE** [comment]
This is my first tests, each take about 90 minutes:

--text "a hamburger"

https://user-images.githubusercontent.com/65137/197421283-d31aa5ee-efeb-45fb-9dd5-b16e46be74a1.mp4

--text "jeweled dagger"

https://user-images.githubusercontent.com/65137/197421294-a7950c2c-e7a0-40a4-8307-0eb1fa0fc78f.mp4

Certainly, a lot more to tune and play with.

**Comment by ashawkey** [comment]
Some results from the pure-pytorch vanilla NeRF backbone:

* a hamburger

https://user-images.githubusercontent.com/25863658/202386706-176fbc90-7043-45b9-86aa-73c4d521d6ce.mp4

* a pineapple

https://user-images.githubusercontent.com/25863658/202386762-956626ed-4e6a-40eb-81c7-affd665d4966.mp4

**Comment by elliottzheng** [comment]
@ashawkey Hi, can you please provide these commands to reproduce the new results video here?

https://github.com/ashawkey/stable-dreamfusion/tree/8d7899ae758e0f683a1cef51b876f2a37cba0c55 

![image](https://user-images.githubusercontent.com/22427645/216226495-e0207d96-3ebb-4fd2-85a1-0279d8b87c42.png)

**Comment by ashawkey** [comment]
@elliottzheng Hi, they are run with the default configs, with prompts like "a superman". You could also refer to this: https://github.com/ashawkey/stable-dreamfusion/issues/128#issuecomment-1413593621.

**Comment by saurabh-08** [comment]
how long does it take to run? Also, does the optional build step (which is failing) makes any difference to the rendering?
