### ISSUE TITLE
Token no longer necessary

### ISSUE THREAD

**Issue by neverix** [ashawkey/stable-dreamfusion#104]
**Is your feature request related to a problem? Please describe.**
The Colab notebook for Stable-DreamFusion can't be run automatically because it requires logging in to HF hub. The API token is no longer required for downloading Stable Diffusion 1 and 2.

**Describe the solution you'd like**
Remove the cell with `auth_token` and remove token handling from the code.

**Describe alternatives you've considered**
It's possible to give users an option to disable the authentication token.

**Comment by ashawkey** [comment]
@neverix Thanks for the feedback! I have removed token requirement in https://github.com/ashawkey/stable-dreamfusion/commit/ea9caac43e2cd748c1c8c79c0f05fe81683c525e.
