### ISSUE TITLE
GUI usage similar to the demmo pinapple video in readme

### ISSUE THREAD

**Issue by vishalghor** [ashawkey/stable-dreamfusion#110]
### Description

I was trying to use the gradio based web gui to use in a similar way as shown in the first sample pineapple video in readme but the resulting web gui only has option to add prompt, set seed and no toption to view the genertaed video form different positions as in the video.

### Steps to Reproduce

1. Run the gradio_app.py 

### Expected Behavior

Resultation web gui similar to the one depicted in example/sample video of pineapple

### Environment

Ubuntu 20 LTS, pytorch 1.13.0, Cuda-11.7

**Comment by ashawkey** [comment]
@vishalghor Hi, the web GUI is different from the local GUI, you should run `main.py` with `--gui` to get the demo video's GUI.
