### ISSUE TITLE
Cannot compile dependencies

### ISSUE THREAD

**Issue by SomeOrdinaryDude** [ashawkey/stable-dreamfusion#116]
### Description

`/usr/local/cuda/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.`

So for whatever reason, anything later than GCC 11 doesn't work? That does not seem right

### Steps to Reproduce

1. Run inference of any kind
2. Refusal to compile

### Expected Behavior

Modules compile, and inference goes on

### Environment

Fedora 37, pytorch and all straight from requirements.txt

**Comment by ashawkey** [comment]
@SomeOrdinaryDude Hi, the latest CUDA only supports [gcc version <= 11](https://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version). You'll have to use a compatible version, or try to add the flag in error message.

**Comment by SomeOrdinaryDude** [comment]
@ashawkey I tried adding the flag, but same error. I suppose I need to add it in a file, and not in the command prompt input, but which file is it? Thanks for help

**Comment by ashawkey** [comment]
I suppose in all the `nvcc_flags` like [here](https://github.com/ashawkey/stable-dreamfusion/blob/main/gridencoder/backend.py#L6).

**Comment by SomeOrdinaryDude** [comment]
Got another issue after setting the flag, but it appears to be the usual fedora jank when it comes to compiling and nvidia. Will try distrobox, but I consider this issue solved then.
