### ISSUE TITLE
Vanilla NeRF v.s. Instant-NGP NeRF

### ISSUE THREAD

**Issue by lcysonya** [ashawkey/stable-dreamfusion#117]
Thanks for the great work!
  
I notice your annotation that Instant-NGP NeRF have faster rendering speed while worse surface quality. But when I use text prompt ,"a hamburger" ,  to train Instant-NGP NeRF and Vanilla NeRF,  the Instant-NGP NeRF get better results. 

Actually， I pick all train commands from the Usage part of readme.md,  and I also change the seed to train several times. I wonder is it an exception(for certrain text prompts) or there are some another settings I missed.

**Comment by ashawkey** [comment]
@lcysonya Hi, many conditions may influence the generation quality, and in general the instant-ngp backbone generates better shapes. The vanilla backbone is still experimental and is intended if you cannot build the cuda extensions.

**Comment by lcysonya** [comment]
Thanks！
