### ISSUE TITLE
Do I have to retrain with every text input

### ISSUE THREAD

**Issue by Kuang-Hiu** [ashawkey/stable-dreamfusion#127]
It's great! So I have a question: I trained with text : "a apple". Now I want get mesh with input is "a yellow apple...". Do I have to retrain with every text input
Thanks!

**Comment by ashawkey** [comment]
@Kuang-Hiu Yes, currently it has to be trained per prompt. But in case the prompts are similar (e.g., only adding a "yellow"), you may finetune from the apple's checkpiont, so it could converge faster (only need to change the color).

**Comment by Kuang-Hiu** [comment]
Thank for your answer!
