### ISSUE TITLE
The config to reproduce the latest results with improvement from Magic3D.

### ISSUE THREAD

**Issue by ybbbbt** [ashawkey/stable-dreamfusion#128]
Hi, ashawkey, thanks for the impressive work!
In the latest readme (8d7899ae758e0f683a1cef51b876f2a37cba0c55), you show that the improvement from Magic3D can greatly boost the quality.
However, it seems that the default setting cannot generate objects with on-par quality (e.g., "a DSLR photo of a squirrel"). 
Would you like to show any example config or scripts that can to reproduce these results?

**Comment by ashawkey** [comment]
@ybbbbt Hi, they are run with the default config, but only using prompts like "a squirrel" (Adding "a DLSR photo of" leads to worse shape in my case). But you do need some luck to get a good result, here are my reproduction with the latest commit:

https://user-images.githubusercontent.com/25863658/216313871-9d816302-2a16-4b61-aba3-0509eee08b9e.mp4
