### ISSUE TITLE
How to reproduce results in demo video？

### ISSUE THREAD

**Issue by jder1234** [ashawkey/stable-dreamfusion#130]
Hi， @ashawkey 

Could you share your options (random seed, iteration num, etc) to reproduce those good results in demo video?

**Comment by ashawkey** [comment]
@jder1234 Hi, they are run with the default config, you only need to change prompts, like "a superman".

**Comment by jder1234** [comment]
@ashawkey  Here is my "superman" with default configs.   The details of texture seems to be lost  in comparison with the superman in the demo.


https://user-images.githubusercontent.com/106365097/216353593-515ca047-2c85-4948-ad22-82b1e7eadb1e.mp4

**Comment by ashawkey** [comment]
They seem quite similar to me? You may try different seeds, or train longer epochs.

**Comment by ashawkey** [comment]
Also, you may increase the network's size (modifying network_grid.py, like using more layers of MLPs).

**Comment by jder1234** [comment]
ok, thanks for your patience.
