### ISSUE TITLE
raymarching composite_rays build error

### ISSUE THREAD

**Issue by flobotics** [ashawkey/stable-dreamfusion#133]
### Description

i pulled the latest stuff from git and wanted to rebuild, but i failed with raymarching composite_rays error.

After struggling a while, i deleted the "const" from line 925 of raymarching.cu file ( https://github.com/ashawkey/stable-dreamfusion/blob/main/raymarching/src/raymarching.cu ). So that the signature matches the declaration in https://github.com/ashawkey/stable-dreamfusion/blob/main/raymarching/src/raymarching.h

After that it builds raymarching and i can run stable-dreamfusion 

### Steps to Reproduce

deleted the "const" from line 925 of raymarching.cu file ( https://github.com/ashawkey/stable-dreamfusion/blob/main/raymarching/src/raymarching.cu ) . So that the signature matches the declaration in https://github.com/ashawkey/stable-dreamfusion/blob/main/raymarching/src/raymarching.h

### Expected Behavior

it builds

### Environment

windows 11, anaconda 3, cuda-11.8

**Comment by ashawkey** [comment]
@flobotics Thanks for reporting the bug!

**Comment by lanzehua** [comment]
So，I wanna know if cuda is not supported, will the project still work?Thank you very much
