### ISSUE TITLE
Question about SDS loss

### ISSUE THREAD

**Issue by subin-kim-cv** [ashawkey/stable-dreamfusion#139]
Hello, thanks for your great work!

I have one question about SDS loss implementation. 

According to the pseudocode presented in Figure 8 of the original paper, the SDS loss involves a dot product of 
"weight(t) * dot(stopgradient[epshat_t - eps], x)". 
However, in the implementation, this dot product is missing, and instead, the loss is simply defined as "weight(t) * epshat_t - eps". 

Please let me know if I misunderstood something :)

Thanks.

**Comment by ashawkey** [comment]
@subin-kim-cv Hi, we use the explicit form in the paper:
$$g = matmul(weight(t) * (-epshat t - eps), grad(x, params)).$$
where the dot (matmul) moves out from the gradient for easy integration with torch's `backward`.

**Comment by subin-kim-cv** [comment]
Oh, I misunderstood. Thanks :)

**Comment by rgxie** [comment]
> @subin-kim-cv Hi, we use the explicit form in the paper: g=matmul(weight(t)∗(−epshatt−eps),grad(x,params)). where the dot (matmul) moves out from the gradient for easy integration with torch's `backward`.
I would like to ask why it is 'matmul(weight(t) * (-epshat_t - eps), grad(x, params))' instead of 'matmul(weight(t) * (epshat_t - eps), grad(x, params))'?

**Comment by rgxie** [comment]
I would like to know why it is 'matmul(weight(t) * (-epshat_t - eps), grad(x, params))' instead of 'matmul(weight(t) * (epshat_t - eps), grad(x, params))'?
