### ISSUE TITLE
why is first stage autoencoder model scaled differently

### ISSUE THREAD

**Issue by nikjetchev** [ashawkey/stable-dreamfusion#14]
https://github.com/ashawkey/stable-dreamfusion/blob/a0c430803192fc8fb5e96b1cd94200601bc16441/nerf/sd.py#L139
Why do we have the 0.18215 constant there? This would make the current repository different than the standard way to use StableDiffusion? Can you please explain the motivation for that? Thanks a lot and keep-up the good work!

**Comment by epi-morphism** [comment]
It's probably a simple mistake. For the record it's supposed to occur _after_ decoding the latents (not before). Unclear how much it changes the output but that's the 'official' way.

**Comment by ashawkey** [comment]
@nikjetchev Hi, I simply followed diffusers' example [here](https://huggingface.co/blog/stable_diffusion).

**Comment by nikjetchev** [comment]
thanks, i found the reference code, it is all correct.
