### ISSUE TITLE
Lucky results seem hard to obtain

### ISSUE THREAD

**Issue by zhaoyuzhi** [ashawkey/stable-dreamfusion#146]
Thanks for implementing the awesome stable-dreamfusion project! Recently, I have tried quite a lot of prompts and trained them with stable-dreamfusion codes on a single A100 GPU card. I found the differences are quite obvious among the trained models from different random initializations.  BTW I use the default settings, e.g.,
```bash
python main.py --text "a pineapple" --workspace trial2 -O2
```

It is quite hard to obtain "lucky results". Is there any idea to improve the generation quality to match the README samples?

Here are some of my results, which are not similar to the samples shown in README:

- a pineapple (training the model 5 times using the same prompt)

https://user-images.githubusercontent.com/13333802/219289370-aea55b4e-f2d2-45f6-a5a0-1b0896eb4abd.mp4

https://user-images.githubusercontent.com/13333802/219289488-0ce252c3-205e-4d93-ab6e-1e098dc39398.mp4

https://user-images.githubusercontent.com/13333802/219289567-e616536a-4acc-4cd6-94e6-5b882dcc886f.mp4

https://user-images.githubusercontent.com/13333802/219289761-f0f62390-c2c4-4596-a8a0-40b6264a1611.mp4

https://user-images.githubusercontent.com/13333802/219289733-82c7e2b6-5969-4f2b-a9f7-a5ec73dc92ee.mp4

- a DSLR photo of a pineapple (training the model 5 times using the same prompt)

https://user-images.githubusercontent.com/13333802/219289870-224462d0-72c3-4d85-ae77-734e9eee0419.mp4

https://user-images.githubusercontent.com/13333802/219289885-9e20b498-2ad0-4805-a60c-42fc6b7447b3.mp4

https://user-images.githubusercontent.com/13333802/219289899-5cb43549-0ae3-4ca2-be17-78ef0f87ddd4.mp4

https://user-images.githubusercontent.com/13333802/219289945-63c8aec0-0fb8-4820-aaa5-9803a9ccad91.mp4

https://user-images.githubusercontent.com/13333802/219289925-eb4285bc-b48f-4e68-97cd-6da027d9c109.mp4

**Comment by ashawkey** [comment]
@zhaoyuzhi Hi, the `-O2` mode is not working well currently, so I recommend you to try `-O` instead. All the examples are generated with `-O`.

**Comment by zhaoyuzhi** [comment]
Thanks for your suggestion @ashawkey 

I can reproduce the pineapple sample shown in the readme now.
