### ISSUE TITLE
Fine tuned stable diffusion model?

### ISSUE THREAD

**Issue by krNeko9t** [ashawkey/stable-dreamfusion#153]
I want to generate some specific object where the origin model may not contain, so i want to fine tune it by some tech like dreambooth. Is it possible to use fine tuned stable diffusion model to train the dreamfusion model?

**Comment by AmanKishore** [comment]
Yes that's possible, you can pass in the `--hf_key` flag: https://github.com/ashawkey/stable-dreamfusion/blob/main/main.py#L56

**Comment by krNeko9t** [comment]
Thank your rapidly response! And sorry for not read the code carefully.

**Comment by AmanKishore** [comment]
No problem! Btw if you want to experiment with dreamfusion check out: https://app.mirageml.com/generate
You can click on advanced settings and try out a hf model!
