### ISSUE TITLE
About the coordinate system

### ISSUE THREAD

**Issue by mdarhdarz** [ashawkey/stable-dreamfusion#154]
The coordinate system used in the sampling is like:
   z
   |
  / — x
y

However, common mesh viewers (e.g. meshlab, blender) use:
   z
   |
  / — y
x

This will lead to a flip of images. That is, if the model render a word on the object, the word will be fliped in the exported mesh.

**Describe the solution you'd like**
1. when export mesh, axis x to -x
2. change the coordinate system in the sampling

**Comment by ashawkey** [comment]
@mdarhdarz Hi, could you provide an example? 
I thought I have fix this problem, but not quite sure:
![image](https://user-images.githubusercontent.com/25863658/220833431-292a3a5f-ef77-4c76-864c-e3d06aec7aae.png)

**Comment by mdarhdarz** [comment]
Thanks a lot! Maybe it's just ok if the rendered images in mesh viewers and validation images are consistent. I also tried modifying "export_mesh" function and achieve similar results.
