### ISSUE TITLE
left side view & right side view

### ISSUE THREAD

**Issue by xuanyuzhang21** [ashawkey/stable-dreamfusion#170]
Thanks for your great project! I find that the stable diffusion fails to generate "left side view" and "right side view", which may cause inconsistency between different views and intensify the multi-face Janus problem. How can I solve this problem?

**Comment by ashawkey** [comment]
@xuanyuzhang21 Unfortunately, I guess there's no other better way except using a better text-to-2D model...

**Comment by Jainam213** [comment]
Cant we use a visual perception prior to get front view side view properly?
See:
https://vpd.ivg-research.xyz/?s=09

Also chineese model composer is coming out soon intrested to see if it solves our problem
