### ISSUE TITLE
Error creating mesh 

### ISSUE THREAD

**Issue by ouerkakaChango** [ashawkey/stable-dreamfusion#181]
### Description

I installed all the requirements.

Generating example 'hamberger' .
`python main.py --text "a hamburger" --workspace trial -O`

Training finished successfully.

Output video successfully.

But generating mesh failed when
```
python main.py --workspace trial -O --test --save_mesh
```
The error 
```
Traceback (most recent call last):
  File "/home/[MyUser]/gitProjects/stable-dreamfusion/main.py", line 149, in <module>
    trainer.save_mesh()
  File "/home/[MyUser]/gitProjects/stable-dreamfusion/nerf/utils.py", line 506, in save_mesh
    self.model.export_mesh(save_path, resolution=self.opt.mcubes_resolution, decimate_target=self.opt.decimate_target)
  File "/home/[MyUser]/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/[MyUser]/gitProjects/stable-dreamfusion/nerf/renderer.py", line 227, in export_mesh
    vertices, triangles = clean_mesh(vertices, triangles)
  File "/home/[MyUser]/gitProjects/stable-dreamfusion/meshutils.py", line 82, in clean_mesh
    m = pml.Mesh(verts, faces)
pymeshlab.pmeshlab.PyMeshLabException: Error while creating mesh: Vertex matrix is empty.
```
seems verts all none, after marching cube.

### Steps to Reproduce

1.
`python main.py --text "a hamburger" --workspace trial -O`

2.
```
python main.py --workspace trial -O --test --save_mesh
```

### Expected Behavior

Output mesh normmaly

### Environment

Ubuntu22.04 ,pytorch '2.0.0+cu117'

**Comment by ashawkey** [comment]
@ouerkakaChango Hi, is the video showing a correct object? This may indicate the generation failed to form a shape.

**Comment by ouerkakaChango** [comment]
> @ouerkakaChango Hi, is the video showing a correct object? This may indicate the generation failed to form a shape.

Yes,the images and .mp4 are correctly a nice hamberger.

**Comment by ashawkey** [comment]
That's strange, maybe you could print out some information like here `File "/home/[MyUser]/gitProjects/stable-dreamfusion/nerf/renderer.py", line 227` to debug?

**Comment by ouerkakaChango** [comment]
> That's strange, maybe you could print out some information like here `File "/home/[MyUser]/gitProjects/stable-dreamfusion/nerf/renderer.py", line 227` to debug?
Not familiar with this...But I tried.
```
   print("### ", len(vertices)," ",len(triangles))
   vertices, triangles = clean_mesh(vertices, triangles)
```
output `### 0 0` .Empty after `vertices, triangles = mcubes.marching_cubes(sigmas, density_thresh)`
Don't know how to check if the density grid is right or wrong, not familiar with torch or its visuialization

**Comment by MathieuTuli** [comment]
This happened to me. It's because `mean_density` [(here)](https://github.com/ashawkey/stable-dreamfusion/blob/9eb8e5b2da090c408fa03ecea9735e61fbe10dd9/nerf/renderer.py#L189) is zero I believe. As a result, you get empty `vertices` and `triangles` ([see here](https://github.com/ashawkey/stable-dreamfusion/blob/9eb8e5b2da090c408fa03ecea9735e61fbe10dd9/nerf/renderer.py#L215)).

For some reason, `mean_density` wasn't updated or saved during training. The workaround is to set `mean_density` to something `<0.1` or something. It will work, and run, but the mesh probably will be a little wonky. It worked for me anyways. Perhaps this is a bug that needs addressing.
