### ISSUE TITLE
DMtet fine-tune in remote service

### ISSUE THREAD

**Issue by lingtengqiu** [ashawkey/stable-dreamfusion#189]
### Description

When I run command
```
python main.py -O --text "A baby bunny sitting on top of a stack of pancakes" --workspace trial_dmtet --dmtet --iters 5000 --init_ckpt trial/checkpoints/df.pth
```
to obtain the fine-tune DMtet mesh, I had the following problem.
```
[F glutil.cpp:338] eglInitialize() failed
```

### Steps to Reproduce

""

### Expected Behavior

""

### Environment

PyTorch1.2.0, CUDA11.3

**Comment by ashawkey** [comment]
@lingtengqiu Hi, this is related to failure of OpenGL installation, you may install the CUDA driver, or use nvidia-docker as suggested in https://github.com/ashawkey/stable-dreamfusion/issues/131.

**Comment by lingtengqiu** [comment]
Thanks

**Comment by zhongjinluo** [comment]
Replace all `dr.RasterizeCudaContext(output_db=False)` to `dr.RasterizeCudaContext()` in `nerf/renderer.py` as suggested in https://github.com/sicxu/Deep3DFaceRecon_pytorch/issues/2#issuecomment-1501123235
