### ISSUE TITLE
<title>default generation with '--seed' failed. TypeError: Cannot cast scalar from dtype('<U4') to dtype('int64') according to the rule 'safe'

### ISSUE THREAD

**Issue by r530044129** [ashawkey/stable-dreamfusion#190]
### Description

I use default cmd: python main.py --text "a hamburger" --workspace trial -O, 
Here is the error:
TypeError: composite_rays_train_forward(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: int, arg5: int, arg6: float, arg7:at::Tensor, arg8: at::Tensor, arg9: at::Tensor, arg10: at::Tensor) -> None
![image](https://user-images.githubusercontent.com/22882223/230561309-210fcede-2564-4f42-92e5-82be540a25e1.png)
![image](https://user-images.githubusercontent.com/22882223/230561337-cb45b061-1813-455a-9627-4d6cd82bb117.png)

When i add the parm '--seed', it's failed. Eg. python main.py --text "a hamburger" --workspace trial -O --seed 1024
Here is another error:
TypeError: Cannot cast scalar from dtype('<U4') to dtype('int64') according to the rule 'safe'
![image](https://user-images.githubusercontent.com/22882223/230560723-996d1da1-be88-4fcb-b5bc-d45c958fa1c8.png)

### Steps to Reproduce

python main.py --text "a hamburger" --workspace trial -O --seed 1024

### Expected Behavior

python main.py --text "a hamburger" --workspace trial -O --seed 1024
work

### Environment

win11, torch 1.13

**Comment by ashawkey** [comment]
@r530044129 Hi, 
1. you need to reinstall `pip install ./raymarching` as I have updated the cuda code.
2. I'll fix it soon, thanks for  reporting!

**Comment by r530044129** [comment]
thanks, it's work

**Comment by r530044129** [comment]
When i add '--seed 123', it's still failed. Although I've already re-compile the raymarching

**Comment by ashawkey** [comment]
Hi, could you provide the error logging?

**Comment by r530044129** [comment]
it's work now, when i git pull the lastest code
