### ISSUE TITLE
Possible improvement regarding the DMTet

### ISSUE THREAD

**Issue by yukangcao** [ashawkey/stable-dreamfusion#194]
Hi Kiui,

Thanks for your great repo and the implementation of the coarse-to-fine baseline. I have noticed that the generated DMTet has the wrong geometry (face), which will also lead to wrong shading during the training. I am not sure if this is your specific design but by multiplying '-1' to the vertices in https://github.com/ashawkey/stable-dreamfusion/blob/main/nerf/renderer.py#L301, we can rectify this issue and achieve improved results. (see the image below for a quick example, which you can generate by setting 'Back-Face' to 'Cull' via meshlab.)

Hope this would help.
![Screen Shot 2023-04-10 at 11 19 54](https://user-images.githubusercontent.com/49137418/230818933-289c6288-f846-4989-a9d3-e7d52cdb6cf1.png)

**Comment by ashawkey** [comment]
@yukangcao Wow thanks for reporting this bug! 
A PR to fix this will be highly appreciated if you are convenient, or I can fix it later.

**Comment by yukangcao** [comment]
> @yukangcao Wow thanks for reporting this bug! A PR to fix this will be highly appreciated if you are convenient, or I can fix it later.

Thanks for your reply! A PR request has been created accordingly for you to check at your convenience. Thanks.

**Comment by ashawkey** [comment]
Thanks for your contribution! I have merged it!
