### ISSUE TITLE
Question about Checkpoint Generation

### ISSUE THREAD

**Issue by genderplugin** [ashawkey/stable-dreamfusion#206]
Hello,

I was just curious, should a checkpoint at the end of training be automatically generated. For example, I ran: 

`python main.py --text a blue bird with a sword in it's beak --workspace birdSword -O2 --w 128 --h 128`

And then when I ran the test prompt, it said that the latest checkpoint was: checkpoints/birdSword/df_ep0100.pth

Then, I tried to do the dmtet fine tuning and pointed to that file path, but that checkpoint does not exist. It also isn't in that folder. I don't fully understand what I'm missing. The terminal used to checkpoint when I ran the --test prompt, but now that I have the mesh it isn't there? Is there something I should change so I can save a checkpoint once I'm done training?

**Comment by ashawkey** [comment]
@genderplugin Hi, I think it says `birdSword/checkpoints/df_ep0100.pth`? You can always use `<workspace>/checkpoints/df.pth` which saves the latest checkpoint.

**Comment by genderplugin** [comment]
@ashawkey thank you I did not know that! For some reason my paperspace snapshot doesn't display a checkpoint in the checkpoints folder so I thought maybe something wasn't saved. Thanks again!
