### ISSUE TITLE
View embedding interpolation implementation

### ISSUE THREAD

**Issue by zhuole1025** [ashawkey/stable-dreamfusion#207]
Thanks for your awesome implementation for DreamFusion! I find that you have implemented most tricks mentioned in the DreamFusion paper. Howerer, the view interpolation trick seems to be missing in your code. I am wondering that adding view prompt interpolation may partly solve the Jenus problem. Further, I notice a recent paper which can be referred to: https://arxiv.org/pdf/2304.04968.pdf.

**Comment by ashawkey** [comment]
@zhuole1025 Hi, I implemented a naive view feature interpolation in the latest code: https://github.com/ashawkey/stable-dreamfusion/blob/main/nerf/utils.py#L442
I have read the paper too, but it requires about 2x diffusion computation (to calculate extra negative prompts) per step, so currently I haven't implemented it.
