### ISSUE TITLE
Removal of grad_clip?

### ISSUE THREAD

**Issue by zhuole1025** [ashawkey/stable-dreamfusion#208]
Hi, I just update with your latest code and find that the grad_clip in train_step.py is removed. I am woderring why since it seems help to solve the Janus problem mentioned in the paper named "debiasing xxx".

**Comment by ashawkey** [comment]
@zhuole1025 Hi, I actually moved the grad clip from latent space to RGB space and all parameters, controlled by `--grad_clip` and `--grad_clip_rgb`. However, I haven't been able to perform enough experiments to verify their effect or best value.

**Comment by zhuole1025** [comment]
@ashawkey Got it, I have run several experiments and found that grad_clip seems to alleviate some multi-face problems, but definitely not for all cases. 
P.S., I just updated the latest code but found that the training speed became extremely slow. It takes ten minutes to finish one epoch compared to one minute before the update. I am not sure which parameters are change due to this update.

**Comment by zhuole1025** [comment]
I found that I made a stupid mistake... I add extra parameters to the train_step function, but forget to add it during the code updates. Thanks a lot!
