### ISSUE TITLE
Better method to append view information

### ISSUE THREAD

**Issue by thuanz123** [ashawkey/stable-dreamfusion#21]
If I understand correctly, the code currently append the view information at the end of the text prompt which is generally not good from my experience. Instead, I append it at the beginning like this "overhead view of a squirrel playing piano".

This is the result with the prompt "a squirrel playing piano, overhead view"
<div style='display: flex; flex-wrap: wrap; column-gap: 0.75rem;'>
<img src='https://s3.amazonaws.com/moonup/production/uploads/1665196244828-noauth.jpeg' width='400' height='400'>
<img src='https://s3.amazonaws.com/moonup/production/uploads/1665196245316-noauth.jpeg' width='400' height='400'>
<img src='https://s3.amazonaws.com/moonup/production/uploads/1665196245065-noauth.jpeg' width='400' height='400'>
<img src='https://s3.amazonaws.com/moonup/production/uploads/1665196245308-noauth.jpeg' width='400' height='400'>
</div>

<br/>
This is the result with the prompt "overhead view of a squirrel playing piano"
<div style='display: flex; flex-wrap: wrap; column-gap: 0.75rem;'>
<img src='https://s3.amazonaws.com/moonup/production/uploads/1665196360423-noauth.jpeg' width='400' height='400'>
<img src='https://s3.amazonaws.com/moonup/production/uploads/1665196360441-noauth.jpeg' width='400' height='400'>
<img src='https://s3.amazonaws.com/moonup/production/uploads/1665196360466-noauth.jpeg' width='400' height='400'>
<img src='https://s3.amazonaws.com/moonup/production/uploads/1665196360465-noauth.jpeg' width='400' height='400'>
</div>

**Comment by thuanz123** [comment]
Also, in the paper author state that only when the angle of camera view less than 60 that they append overhead view. But in the code seem like you append it all the time ?

**Comment by ashawkey** [comment]
@thuanz123 Hi, thanks for the insight! 
1. This is worth trying, but they also append something like "a DSLR photo of" before the prompt, maybe this also needs some tests.
2. I think no? you can check the `get_view_direction` function in `provider.py`, we assign a dir label to each camera pose, and overhead is only appended if `thetas <= 30`. (The angle notation is a little different, I used [0, 180] for the elevation where 0 is the top view...)

**Comment by thuanz123** [comment]
Ah OK thanks, I missed that piece of code. Close this issue then
