### ISSUE TITLE
SDS on identity matrix

### ISSUE THREAD

**Issue by jh27kim** [ashawkey/stable-dreamfusion#212]
Hi, I am directly applying SDS in image space, which was also tried in the original paper where g(theta) = I, g would be an identity matrix.

But it seems to possess some artifacts... 

What possibly could have gone wrong ? Any ideas? 
Thanks

Caption: "Squirrel snowboarding"
Guidance scale: 10
Step: 2500

Result image:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/58447982/232953319-8282fff8-dd69-4714-aea3-ee9a9b8f62f5.png">

Original image:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/58447982/232953486-48544d03-f6da-4eac-9f52-1713d9282699.png">

**Comment by ashawkey** [comment]
@jh27kim Hi, this is actually once discussed here: https://github.com/ashawkey/stable-dreamfusion/issues/96
The gradient has to pass the encoder of stable-diffusion's VAE, which makes it unstable. Training in latent space can be very helpful.

**Comment by jh27kim** [comment]
Thanks for the clarification. It works well.
