### ISSUE TITLE
The texture when I use fine-tuning with DMTet (mesh representation)

### ISSUE THREAD

**Issue by ug-kim** [ashawkey/stable-dreamfusion#216]
I have some questions about DMTET fine-tuning.

DMTet makes mesh as final representations; I'm curious how we learn the texture of mesh at DMTet fine-tuning stages.

And how do you render mesh rendering with geometry and texture?

It would be appreciated to tell me about the method and code part.

Thanks for sharing your awesome work.

**Comment by ashawkey** [comment]
@ug-kim Hi, the code of DMTet is majorly adapted from [nvdiffrec](https://github.com/NVlabs/nvdiffrec). You may check their paper for a detailed explanation. In summary, we still use the 3D hashgrid from NeRF stage to encode the texture during training, and only bake it into 2D texture images at exporting.
