### ISSUE TITLE
Questions about the matrix `mvp` in dataloading

### ISSUE THREAD

**Issue by hytseng0509** [ashawkey/stable-dreamfusion#221]
Hi, thanks for sharing such an amazing implementation!

I have a question about the projection matrix computation [here](https://github.com/ashawkey/stable-dreamfusion/blob/49c3d4fa01d68a4f027755acf94e1ff6020458cc/nerf/provider.py#L222) for the `mvp` matrix.
Specifically, could you elaborate more about: how is the projection matrix formulated in this way (especially the third and fourth rows)?
(My understanding is that this is for the rasterization from the `nvdiffrast` library. Is that correct?)

**Comment by ashawkey** [comment]
@hytseng0509 Hi, you can find a good explanation of MVP [here](http://www.songho.ca/opengl/gl_projectionmatrix.html).

**Comment by hytseng0509** [comment]
Thanks for the information!
