### ISSUE TITLE
Image Condition Errors using Examples Scripts

### ISSUE THREAD

**Issue by taeyeopl** [ashawkey/stable-dreamfusion#231]
### Description

The provided scripts don't work with the below errors. 

https://github.com/ashawkey/stable-dreamfusion/blob/4171f00c8d1721bb4645bad902b8b4d6fae3cef5/scripts/run_image1.sh#L3

CUDA_VISIBLE_DEVICES=1 python main.py -O --image data/catstatue_rgba.png --workspace trial_image_catstatue --iters 5000
Namespace(text=None, negative='', O=True, O2=False, test=False, eval_interval=1, workspace='trial_image_catstatue', guidance='zero123', seed=None, image='data/catstatue_rgba.png', known_view_interval=2, guidance_scale=3, save_mesh=False, mcubes_resolution=256, decimate_target=50000.0, dmtet=False, tet_grid_size=128, init_ckpt='', iters=5000, lr=0.001, ckpt='latest', cuda_ray=True, taichi_ray=False, max_steps=1024, num_steps=64, upsample_steps=32, update_extra_interval=16, max_ray_batch=4096, warmup_iters=0, jitter_pose=False, uniform_sphere_rate=0, grad_clip=-1, grad_clip_rgb=-1, bg_radius=1.4, density_activation='softplus', density_thresh=0.1, blob_density=10, blob_radius=0.5, backbone='grid', optim='adan', sd_version='2.1', hf_key=None, fp16=True, vram_O=False, w=64, h=64, known_view_scale=1.5, known_view_noise_scale=0.002, dmtet_reso_scale=8, bound=1, dt_gamma=0, min_near=0.01, radius_range=[1.0, 1.5], theta_range=[45, 105], phi_range=[-180, 180], fovy_range=[60, 60], default_radius=1.2, default_theta=90, default_phi=0, default_fovy=60, progressive_view=True, progressive_level=True, angle_overhead=30, angle_front=60, t_range=[0.02, 0.5], lambda_entropy=0.001, lambda_opacity=0, lambda_orient=10, lambda_tv=0, lambda_wd=0, lambda_mesh_normal=0.5, lambda_mesh_laplacian=0.5, lambda_guidance=0.02, lambda_rgb=10, lambda_mask=5, lambda_normal=0, lambda_depth=0.1, lambda_2d_normal_smooth=0, gui=False, W=800, H=800, radius=3, fovy=60, light_theta=60, light_phi=0, max_spp=1, full_radius_range=[1.0, 1.5], full_theta_range=[45, 105], full_phi_range=[-180, 180], full_fovy_range=[60, 60])
NeRFNetwork(
  (encoder): GridEncoder: input_dim=3 num_levels=16 level_dim=2 resolution=16 -> 2048 per_level_scale=1.3819 params=(6098120, 2) gridtype=hash align_corners=False interpolation=smoothstep
  (sigma_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=32, out_features=64, bias=True)
      (1): Linear(in_features=64, out_features=64, bias=True)
      (2): Linear(in_features=64, out_features=4, bias=True)
    )
  )
  (encoder_bg): FreqEncoder: input_dim=3 degree=6 output_dim=39
  (bg_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=39, out_features=32, bias=True)
      (1): Linear(in_features=32, out_features=3, bias=True)
    )
  )
)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/miruware/ssd_4tb/diffusion/workspace/stable-dreamfusion/main.py:261 in <module>            │
│                                                                                                  │
│   258 │   │   │   guidance = StableDiffusion(device, opt.fp16, opt.vram_O, opt.sd_version, opt   │
│   259 │   │   elif opt.guidance == 'zero123':                                                    │
│   260 │   │   │   from guidance.zero123_utils import Zero123                                     │
│ ❱ 261 │   │   │   guidance = Zero123(device, opt.fp16, opt.vram_O, opt.t_range)                  │
│   262 │   │   elif opt.guidance == 'clip':                                                       │
│   263 │   │   │   from guidance.clip_utils import CLIP                                           │
│   264 │   │   │   guidance = CLIP(device)                                                        │
│                                                                                                  │
│ /home/miruware/ssd_4tb/diffusion/workspace/stable-dreamfusion/guidance/zero123_utils.py:80 in    │
│ __init__                                                                                         │
│                                                                                                  │
│    77 │   │                                                                                      │
│    78 │   │   self.config = OmegaConf.load(config)                                               │
│    79 │   │   # TODO: seems it cannot load into fp16...                                          │
│ ❱  80 │   │   self.model = load_model_from_config(self.config, ckpt, device=self.device, vram_   │
│    81 │   │                                                                                      │
│    82 │   │   # timesteps: use diffuser for convenience... hope it's alright.                    │
│    83 │   │   self.num_train_timesteps = self.config.model.params.timesteps                      │
│                                                                                                  │
│ /home/miruware/ssd_4tb/diffusion/workspace/stable-dreamfusion/guidance/zero123_utils.py:35 in    │
│ load_model_from_config                                                                           │
│                                                                                                  │
│    32 # load model                                                                               │
│    33 def load_model_from_config(config, ckpt, device, vram_O=False, verbose=False):             │
│    34 │                                                                                          │
│ ❱  35 │   pl_sd = torch.load(ckpt, map_location='cpu')                                           │
│    36 │                                                                                          │
│    37 │   if 'global_step' in pl_sd and verbose:                                                 │
│    38 │   │   print(f'[INFO] Global Step: {pl_sd["global_step"]}')                               │
│                                                                                                  │
│ /home/miruware/anaconda3/envs/dreamfusion/lib/python3.9/site-packages/torch/serialization.py:705 │
│ in load                                                                                          │
│                                                                                                  │
│    702 │   │   │   # If we want to actually tail call to torch.jit.load, we need to              │
│    703 │   │   │   # reset back to the original position.                                        │
│    704 │   │   │   orig_position = opened_file.tell()                                            │
│ ❱  705 │   │   │   with _open_zipfile_reader(opened_file) as opened_zipfile:                     │
│    706 │   │   │   │   if _is_torchscript_zip(opened_zipfile):                                   │
│    707 │   │   │   │   │   warnings.warn("'torch.load' received a zip file that looks like a To  │
│    708 │   │   │   │   │   │   │   │     " dispatching to 'torch.jit.load' (call 'torch.jit.loa  │
│                                                                                                  │
│ /home/miruware/anaconda3/envs/dreamfusion/lib/python3.9/site-packages/torch/serialization.py:242 │
│ in __init__                                                                                      │
│                                                                                                  │
│    239                                                                                           │
│    240 class _open_zipfile_reader(_opener):                                                      │
│    241 │   def __init__(self, name_or_buffer) -> None:                                           │
│ ❱  242 │   │   super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_bu  │
│    243                                                                                           │
│    244                                                                                           │
│    245 class _open_zipfile_writer_file(_opener):                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### Steps to Reproduce

1. Run the below scripts

https://github.com/ashawkey/stable-dreamfusion/blob/4171f00c8d1721bb4645bad902b8b4d6fae3cef5/scripts/run_image1.sh#L3

### Expected Behavior

Run without errors

### Environment

Ubuntu 18.04, Pytorch 1.12.1. CUDA 11.3

**Comment by ashawkey** [comment]
@taeyeopl Hi, I guess your zero-1-to-3 checkpoint is corrupted. You could try to download it again.

**Comment by taeyeopl** [comment]
Hi, @ashawkey
Thanks for your quick response. As you mentioned my checkpoint was corrupted. 

If anyone has a similar same problem, recommend using the below link from the author of zero-1-to-3!
https://cv.cs.columbia.edu/zero123/assets/105000.ckpt
