### ISSUE TITLE
Image to 3D: Zero123 seems to just use initial view

### ISSUE THREAD

**Issue by mhale1** [ashawkey/stable-dreamfusion#232]
### Description

Everything seems to run without error, but Zero123 doesn't seem to get loaded or generate new views. So it is doing image to 3D, but just from the one initial view. Is this the expected current state? There seems to be more code for changing the view, but also a comment about the Zero123 model not loading in fp16.  Glad to see you are still working on this repo. It seems very close to being usable as a real time saver for 3D work.
![temp](https://user-images.githubusercontent.com/5043964/234461716-8bd1e6a3-ad2c-4258-b8af-905539572c0e.png)

https://user-images.githubusercontent.com/5043964/234461737-0b32c8cc-9d0c-4dac-98bf-a21e30e9e565.mp4

### Steps to Reproduce

Just follow steps in readme for image to 3D.

### Expected Behavior

The Zero123 model is loaded and generates new views to improve the image to 3D behavior.

### Environment

Google Colab

**Comment by ashawkey** [comment]
@mhale1 Hi, yes this is still a problem that I'm looking into, I'll update the code if I can get better results.

**Comment by NasirKhalid24** [comment]
This might be a feature of the SDS being mode seeking rather than an explicit bug

**Comment by yanty123** [comment]
I found that the generation is bad facing novel views (compared to the original codes from zero 1-to-3)， especially the cars.

**Comment by mhale1** [comment]
![temp](https://user-images.githubusercontent.com/5043964/235280333-46ea1451-4044-402a-8957-901240a81f96.gif)

These are the results from raw Zero123. I would think we could just pregenerate a variety of views like this and then just use each one of them for an epoch to bake them into the NeRF from the appropriate angle. I feel like this repo is very close to being awesome.

**Comment by mhale1** [comment]
My impression from ashawkey's comment in the code is that this bug is a temporary technicality from like a different file format used in Zero123 or something. Based on memory usage I don't think the model is successfully loading currently.

**Comment by yanty123** [comment]
> 

Hi mhale1, I found that if we input a pre-processes image from the raw zero 1to3, this code will generate a good novel view. However, if I change the input format, the nerf process will be led to worse situation.

**Comment by yxymessi** [comment]
> 

Hi yanty123,  l would like to know what's the meaning of pre-processes image( rgba format?).

**Comment by mhale1** [comment]
@yxymessi They pre process your initial image to remove the background and extract a depth map to help guide the NeRF generation.

**Comment by mhale1** [comment]
@voletiv Thanks for the PR. It helps a little I think. But I think we're still missing something big and simple.

Here are the results from my image in stable-dreamfusion after your fix.

https://user-images.githubusercontent.com/5043964/236643759-b3b0f8e0-0eae-4dd0-8d10-ea2c9abf2525.mp4

Here are the results from the 3D reconstruction in the zero123 repo.

https://user-images.githubusercontent.com/5043964/236643775-95743141-8cb6-40cf-a9eb-28c29ef517d1.mp4

I haven't looked closely yet, but at a glance of memory usage I'm still not even sure this repo is actually using the zero123 model. The memory usage is low, about 16 GB. But the zero123 model needs 20 GB. I think the improvement after your fix might just be from it making some reasonable symmetry assumptions from the depth map guess and then having some color bleed through to the other side of the NeRF.

By comparison, the 3D reconstruction in the Zero123 repo really appears to understand the desired structure of the object from multiple views.

So the ironic situation is that both repos are very close to being useful for image to 3D, but in different ways and as of now the result is generally unusable. The Zero123 repo really appears to use the other views it generates to significant effect, but has terrible final NeRF quality and mesh export. This repo appears to not leverage the potential benefit from the multiple views it should be able to generate, but has great final NeRF quality/cleanup/export.

**Comment by yxymessi** [comment]
> @yxymessi They pre process your initial image to remove the background and extract a depth map to help guide the NeRF generation.

Acutally you can pre-process image in this repo by running  preprocess_image.py。Acutally i find out that even with these preprocessing, we can now generate better results for  symmetric objects. However, for some more difficult object such as bird, now we can just get terrible results.

**Comment by yanty123** [comment]
> @voletiv Thanks for the PR. It helps a little I think. But I think we're still missing something big and simple.
> 
> Here are the results from my image in stable-dreamfusion after your fix.
> 
>  df_ep0100_rgb.1.mp4 
> Here are the results from the 3D reconstruction in the zero123 repo.
> 
>  step_100.1.mp4 
> I haven't looked closely yet, but at a glance of memory usage I'm still not even sure this repo is actually using the zero123 model. The memory usage is low, about 16 GB. But the zero123 model needs 20 GB. I think the improvement after your fix might just be from it making some reasonable symmetry assumptions from the depth map guess and then having some color bleed through to the other side of the NeRF.
> 
> By comparison, the 3D reconstruction in the Zero123 repo really appears to understand the desired structure of the object from multiple views.
> 
> So the ironic situation is that both repos are very close to being useful for image to 3D, but in different ways and as of now the result is generally unusable. The Zero123 repo really appears to use the other views it generates to significant effect, but has terrible final NeRF quality and mesh export. This repo appears to not leverage the potential benefit from the multiple views it should be able to generate but has great final NeRF quality/cleanup/export.

@mhale1 HI. I have the same problem. Could you please share your process for using zero123's 3D reconstruction? How could I  reconstruct any single image without the transform file of camera poses like the demo in zero123?

**Comment by ashawkey** [comment]
@mhale1 @yxymessi  @NasirKhalid24  Hi all, you could try the latest commit:

https://user-images.githubusercontent.com/25863658/236713150-0ea4ae8b-7d7a-4442-b45b-55ad69bc0420.mp4

We are still trying to improve the quality.

As for the memory, the original checkponit ports both EMA and non-EMA weights, but inference will only use EMA. So I deleted the non-EMA weights to load it into 16GB GPU memory.

**Comment by mhale1** [comment]
@ashawkey I confirmed I get the same result. Amazing! And on 16GB!

I'm excited about your future improvements, but I think this already crosses a threshold of usefulness for people. This is totally usable as a starting mesh for fun and fast detail sculpting and painting.

I'm still on the waitlist for NVidia's and Luma's text to 3D. But now this repo is better, with more features, more image models supported, and you get state of the art image to 3D on 16GB!

So, skimming through your change, the fix was to add loss for the 3D normals and change the loss weight for depth, mask, rgb?

Super cool. Thank you for your continued efforts. I'm excited to use it more.

**Comment by yxymessi** [comment]
> 

Thanks again for the wonderful wrok and continued efforts.

**Comment by fafa2015** [comment]
Does anyone know why my zero123 does not generate a new view? I installed all libraries and ckpt as required, and can generate web pages and load an image, but when I click generate, it keeps generating, and it never appears for a long, long time. new view
