### ISSUE TITLE
OpenPose Integration for Quality 3D Character Creation (experimental)

### ISSUE THREAD

**Issue by timsterzizzle** [ashawkey/stable-dreamfusion#235]
Would it be possible to integrate openpose to generate quality (front, back, side-L, side-R) views of 3d character? My hypothesis is that this would increase the quality of the output for 3d character generating tasks. A highly experimental hypothesis.

I would integrate this myself but I am having a hard time grasping exactly how the diffusion pipeline is implemented.

From my understanding, the system is creating an 'average' volume synthesized from 4 views (front, back, side-L, side-R)

I have tried adjusting what the system prepends to the prompt but my assumption is that stable-diffusion wasn't trained really well on poses of things.

Also, you dah GOAT.

**Comment by timsterzizzle** [comment]
@ashawkey thanks for the response, seems my hypothesis is wrong. if you don't mind, and have the time, how did you implement controlnet into the workflow? did you use the zero123 method with a single posed image you created with controlnet? My idea would be to add control-net to stable diffusion when it is called during training.

--or--

Use controlnet to create a series of poses of the same character using a template like below, then using photogrammetry to turn it 3d. I have a rough template created and ran it through controlnet, back side view is still obfuscated which makes me think a "loose" version of photogrammetry that can interpolate images (roughly stable- dreamfusion) would be ideal. Just some thoughts.

![pose_2023_04_29_19_18_51](https://user-images.githubusercontent.com/43685855/236293068-4c5458b3-422b-4a50-9a99-7dc586d414e3.png)

**Comment by ashawkey** [comment]
I'm also using controlnet + stable-diffusion, and use a 3D skeleton to provide poses from different views. You can find that part of code [here](https://github.com/ashawkey/3d_human_poser),

**Comment by PetroRudyi** [comment]
Hello.

I still have a question, how can I use pose to Dreamfusion? Maybe try img2mesh with controlNet model from HF and add prompt? Like "superman"?

**Comment by timsterzizzle** [comment]
@ashawkey I am going to try controlnet with multiple poses with the new zero123 multi-pictures and will report back
@PetroRudyi Controlnet+stable-diffusion-webui = posed image, push posed image into zero123

**Comment by ashawkey** [comment]
Glad to hear that! But the current multi-view zero123 is still experimental, and you may need to tune its performance.
I have tried rendering coco-style pose image from the 3d skeleton, and use pose image as input to controlnet + stable diffusion.
