### ISSUE TITLE
Understanding image and text conditioned generation

### ISSUE THREAD

**Issue by Homagn** [ashawkey/stable-dreamfusion#237]
I was trying to understand the difference between 

1. python main.py -O --image hamburger_rgba.png --text "a DSLR photo of a delicious hamburger" --workspace trial_image_text
2. python main.py -O --text "a DSLR photo of a delicious hamburger" --workspace trial_image_text

In 1, does the model truly receive any additional information compared to 2? I was trying to trace the flow of information but it seems anyways it just uses stable diffusion to generate the image corresponding to text, or does it actually combine the information with hamburger_rgba.png image file in some way? Please clarify if possible and point to the region where it passing the additional information

**Comment by ashawkey** [comment]
@Homagn Hi, the image will be used to perform RGB loss and mask loss from a fixed viewpoint. However, the performance in this repo is not well tuned now for both image and text input, you may try [make-it-3d](https://github.com/junshutang/Make-It-3D) instead.

**Comment by claforte** [comment]
@ashawkey made great progress integrating zero123 for 2D->3D. Closing this issue since @Homagn can debug the code flow themselves.
