### ISSUE TITLE
muti-object generation cannot obtain a good rgb result

### ISSUE THREAD

**Issue by YuanSnowing** [ashawkey/stable-dreamfusion#240]
I used dreamfusion to generate an image of "a cat with fish in mouth", and got an RGB image with only fish(may be two fishes)  and a depth image with seemly right content, like this
![image](https://user-images.githubusercontent.com/53067358/236108749-2d4ab45a-ec95-4f1c-9c5f-912d0138dd3d.png)
I wonder why will this happen, is it caused by the week diffusion model or something else?

**Comment by YuanSnowing** [comment]
In the new version code, I found this problem has been solved. but I am still curious about this phenomenon

**Comment by ashawkey** [comment]
@YuanSnowing Hi, actually I guess this is quite random... now we randomly turn on/off background model during training, so the foreground object are less likely to get covered by background.

**Comment by YuanSnowing** [comment]
Thank you very much!
