### ISSUE TITLE
Segment mesh on parts (automatically define which part/side of a mesh we want to export)

### ISSUE THREAD

**Issue by Pashtetickus** [ashawkey/stable-dreamfusion#250]
Hi!

Could you pls give me a hint if there is a way to find and cut/export specific part of a generated model? Like if i wanted to create a 3D model (mesh) of a human head and then export just the **face** part - just the **face** surface for this generated 3D head - how could this be done in an automated way? Maybe there are some ways to use normal directions? 
I'm trying to google it, but it seems like a non-trivial thing and i haven't worked with meshes and 3D stuff before.

Thank you.

**Comment by ashawkey** [comment]
Hi, I guess there is no automatic and perfect way of doing this, since we aim at general object generation. You may try some face-specific methods.
