### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'log_ptr'

### ISSUE THREAD

**Issue by cwwjyh** [ashawkey/stable-dreamfusion#251]
### Description

Follow your steps to create the virtual environment and so on, but when training the below, i get the error in picture
## train
# pass in the processed <image>_rgba.png by --image and do NOT pass in --text to enable zero-1-to-3 backend.
python main.py -O --image <image>_rgba.png --workspace trial_image --iters 5000
![image](https://github.com/ashawkey/stable-dreamfusion/assets/26154160/8de00cdf-4a68-4bdc-96ad-675ec1f94110)

## train
# pass in the processed <image>_rgba.png by --image and do NOT pass in --text to enable zero-1-to-3 backend.
python main.py -O --image <image>_rgba.png --workspace trial_image --iters 5000

### Expected Behavior

training for successful

### Environment

Package                     Version
--------------------------- ------------
absl-py                     1.4.0
accelerate                  0.19.0
aiofiles                    23.1.0
aiohttp                     3.8.4
aiosignal                   1.3.1
antlr4-python3-runtime      4.9.3
anyio                       3.6.2
async-timeout               4.0.2
attrs                       23.1.0
beautifulsoup4              4.12.2
cachetools                  5.3.0
carvekit-colab              4.1.0
certifi                     2023.5.7
charset-normalizer          3.1.0
click                       8.1.3
clip                        1.0
cmake                       3.26.3
contourpy                   1.0.7
cycler                      0.11.0
dearpygui                   1.9.1
debugpy-run                 1.6
diffusers                   0.16.1
einops                      0.6.1
fastapi                     0.95.1
filelock                    3.12.0
fonttools                   4.39.3
freqencoder                 0.0.0
frozenlist                  1.3.3
fsspec                      2023.5.0
ftfy                        6.1.1
gdown                       4.7.1
google-auth                 2.17.3
google-auth-oauthlib        1.0.0
gridencoder                 0.0.0
grpcio                      1.54.0
h11                         0.14.0
huggingface-hub             0.14.1
idna                        3.4
imageio                     2.28.1
imageio-ffmpeg              0.4.8
importlib-metadata          6.6.0
importlib-resources         5.12.0
Jinja2                      3.1.2
joblib                      1.2.0
kiwisolver                  1.4.4
kornia                      0.6.12
lightning-utilities         0.8.0
lit                         16.0.3
loguru                      0.7.0
Markdown                    3.4.3
markdown-it-py              2.2.0
MarkupSafe                  2.1.2
matplotlib                  3.7.1
mdurl                       0.1.2
mpmath                      1.3.0
multidict                   6.0.4
networkx                    3.1
ninja                       1.11.1
numpy                       1.24.3
nvdiffrast                  0.3.0
nvidia-cublas-cu11          11.10.3.66
nvidia-cuda-cupti-cu11      11.7.101
nvidia-cuda-nvrtc-cu11      11.7.99
nvidia-cuda-runtime-cu11    11.7.99
nvidia-cudnn-cu11           8.5.0.96
nvidia-cufft-cu11           10.9.0.58
nvidia-curand-cu11          10.2.10.91
nvidia-cusolver-cu11        11.4.0.1
nvidia-cusparse-cu11        11.7.4.91
nvidia-nccl-cu11            2.14.3
nvidia-nvtx-cu11            11.7.91
oauthlib                    3.2.2
omegaconf                   2.3.0
opencv-python               4.7.0.72
packaging                   23.1
Pillow                      9.5.0
pip                         23.1.2
protobuf                    3.20.3
psutil                      5.9.5
pyasn1                      0.5.0
pyasn1-modules              0.3.0
pydantic                    1.10.7
Pygments                    2.15.1
PyMCubes                    0.1.4
pymeshlab                   2022.2.post3
pyparsing                   3.0.9
PySocks                     1.7.1
python-dateutil             2.8.2
python-multipart            0.0.6
pytorch-lightning           2.0.2
PyYAML                      6.0
raymarching                 0.0.0
regex                       2023.5.5
requests                    2.30.0
requests-oauthlib           1.3.1
rich                        13.3.5
rsa                         4.9
scikit-learn                1.2.2
scipy                       1.10.1
sentencepiece               0.1.99
setuptools                  58.1.0
shencoder                   0.0.0
six                         1.16.0
sniffio                     1.3.0
soupsieve                   2.4.1
starlette                   0.26.1
sympy                       1.11.1
taming-transformers-rom1504 0.0.6
tensorboard                 2.13.0
tensorboard-data-server     0.7.0
tensorboardX                2.6
threadpoolctl               3.1.0
timm                        0.6.13
tokenizers                  0.13.3
torch                       2.0.1
torch-ema                   0.3
torchmetrics                0.11.4
torchvision                 0.15.2
tqdm                        4.65.0
transformers                4.28.1
trimesh                     3.21.6
triton                      2.0.0
typing_extensions           4.5.0
urllib3                     2.0.2
uvicorn                     0.22.0
wcwidth                     0.2.6
Werkzeug                    2.3.4
wheel                       0.40.0
xatlas                      0.0.7
yarl                        1.9.2
zipp                        3.15.0

**Comment by voletiv** [comment]
Your image name is wrong, you wrote "cactus__rgba.png" (instead of "cactus_rgba.png" I think)
