### ISSUE TITLE
What is your train paramter to get the great results as the ones in the README.md show?

### ISSUE THREAD

**Issue by dedoogong** [ashawkey/stable-dreamfusion#252]
Hi @ashawkey , first I really want to say thank you for your hard and great works.

I've tried a lot of prompts but I got only low quality or ugly 3d meshes. 
Can you share some detailed parameters and what additional models/version you used(Text-to-3D)?

a rabbit, animated movie character, high detail 3d model
a DSLR photo of a delicious hamburger
a highly detailed stone bust of Theodoros Kolokotronis
a small saguaro cactus planted in a clay pot

I really want to get better quality 3d mesh~!

Thank you so much!

**Comment by ashawkey** [comment]
@dedoogong Hi, you can find the commands under `scripts/`. Multiple runs with different seeds may be needed for good results, as the performance can be random.
