### ISSUE TITLE
The quality of rendernig images  is not good

### ISSUE THREAD

**Issue by cwwjyh** [ashawkey/stable-dreamfusion#254]
**Is your feature request related to a problem? Please describe.**

The quality of rendering images is not good  as your presented in"image-to-3d-0123.mp4 "

I use this command: **python main.py -O --image <image>_rgba.png --workspace trial_image --iters 500**
The result is not good as your presented in "image-to-3d-0123.mp4", the result as following:  
Do you have any tricks or parameters change?
 
![df_ep0050_0004_rgb](https://github.com/ashawkey/stable-dreamfusion/assets/26154160/b7fb6056-3c4e-46fc-bb07-def83e094c30)

![df_ep0050_0003_rgb](https://github.com/ashawkey/stable-dreamfusion/assets/26154160/41de57eb-79c2-42fe-bad5-ddb56c64c6d4)

![df_ep0050_0002_rgb](https://github.com/ashawkey/stable-dreamfusion/assets/26154160/68bab387-1e74-4a7d-b409-0324c0c95bce)

**Comment by saullas** [comment]
I get roughly the same results with my photo, even after 5000 or 20000 iterations. How many iterations should be enough for high res (and accurate) result or is there any setting to increase resolution or anything? @ashawkey @cwwjyh
