### ISSUE TITLE
Fine-tuned diffusion prior for image to 3D

### ISSUE THREAD

**Issue by pushkalkatara** [ashawkey/stable-dreamfusion#255]
Hi, Thanks for the amazing work.

Is there a way to use a fine-tuned diffusion prior for our custom image?

For instance, approaches like [multi-concept](https://www.cs.cmu.edu/~custom-diffusion/) diffusion allows fine-tuning diffusion models for our concepts. Using this prior might produce better renders while sds sampling.

**Comment by ashawkey** [comment]
@pushkalkatara Hi, you can use any stable-diffusion based models on huggingface hub, with the `--hf_key` option.

**Comment by pushkalkatara** [comment]
Thanks for pointing it out @ashawkey . Closing this issue.
