### ISSUE TITLE
Condition the Zero123 model

### ISSUE THREAD

**Issue by hytseng0509** [ashawkey/stable-dreamfusion#258]
Hi,

I'm wondering why different signs of the azimuth angle are assigned to the second and third terms to condition the Zero123 model [here](https://github.com/ashawkey/stable-dreamfusion/blob/04062c9e646ce65516ce02e2f9dd3f4bcf69c867/guidance/zero123_utils.py#L177)?

Thanks

**Comment by voletiv** [comment]
The azimuth in Zero123 is in the opposite direction of that in NeRF. So the value of azimuth to be fed to Zero123 should be negative of that of NeRF. Hence, we feed `-azimuth` in the second term. The third term has a cosine in it, so it will output the same value for `azimuth` and `-azimuth`, so we ignored it.
