### ISSUE TITLE
no module: huggingface_hub

### ISSUE THREAD

**Issue by agustincaniglia** [ashawkey/stable-dreamfusion#26]
running the first cell gives me this:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-25c68fb44eae>](https://localhost:8080/#) in <module>
      1 #@title login to huggingface to download stable diffusion
----> 2 from huggingface_hub import notebook_login
      3 from google.colab import output
      4 
      5 output.enable_custom_widget_manager()

ModuleNotFoundError: No module named 'huggingface_hub'

**Comment by Duemellon** [comment]
Same issue : L

**Comment by SilkySnark** [comment]
'!pip install huggingface_hub' solved this issue for me

**Comment by Duemellon** [comment]
I don't see that listed in the collab code. Do I just edit it? > Setup > Login to huggingface to download stable diffusion??

_from huggingface_hub import notebook_login
from google.colab import output
**pip install huggingface_hub**
output.enable_custom_widget_manager()
notebook_login()_

**Comment by SilkySnark** [comment]
I created my own notebook and added another cell where I run this command.
But I think you can add it wherever you want - just make sure to run it before installing

**Comment by agustincaniglia** [comment]
I tried doing that but it sayd something about wrong syntax. As I don't know anything about code, it would be good if it was there by default. thanks.

**Comment by agustincaniglia** [comment]
okay I was able to run it but I can't find the .obj

**Comment by ashawkey** [comment]
Oh I made a careless mistake yesterday. It has been fixed.
