### ISSUE TITLE
the result of rendernig is not good

### ISSUE THREAD

**Issue by cwwjyh** [ashawkey/stable-dreamfusion#261]
**Is your feature request related to a problem? Please describe.**

 I  try the commands in scripts as run_image.sh. But the result of rendering video is not good. Can you give me some advice?

https://github.com/ashawkey/stable-dreamfusion/assets/26154160/8dfc0e62-e546-4c56-9b46-f02e3057e932

**Comment by stas-polukeev** [comment]
@cwwjyh hey. You might wanna look at this issue, which is basically the same (https://github.com/ashawkey/stable-dreamfusion/issues/232). The thing is, image to 3d is still work in progress, but as you can see in the issue it`s getting better.

**Comment by cwwjyh** [comment]
Ok, I'll try it. Thank you!
