### ISSUE TITLE
Working camera angles parameters

### ISSUE THREAD

**Issue by Pashtetickus** [ashawkey/stable-dreamfusion#275]
Hi!

Could anyone help with the angles? I'd like to work for example just on the front part of the object - what parameters should i specify? Maybe `phi_range` from `0` to `90` for NeRF? What else could work? And what will it be for the `Zero123`? 

Thank you!

**Comment by claforte** [comment]
> I'd like to work for example just on the front part of the object - what parameters should i specify?
This would a polar of 90, azimuth of 0, and values surrounding it, e.g. polar of [45,90+45] and azimuth of [-45,45] would cover 45 degrees along each axis around the frontal view.

This code refers to theta for polar, phi for azimuth. I'll fix the arguments' docs in my next PR. Here's an excerpt:

```
parser.add_argument('--theta_range', type=float, nargs='*', default=[45, 105], help="training camera range along the polar angles (i.e. up and down). See advanced.md for details.")
    parser.add_argument('--phi_range', type=float, nargs='*', default=[-180, 180], help="training camera range along the azimuth angles (i.e. left and right). See advanced.md for details.")    
```

@voletiv recently documented the conventions in https://github.com/ashawkey/stable-dreamfusion/blob/main/assets/advanced.md. My next PR will add a clarification.
