### ISSUE TITLE
Question/Bug About Using SDS sampling

### ISSUE THREAD

**Issue by JulianKnodt** [ashawkey/stable-dreamfusion#279]
### Description

I am trying to use score distillation sampling with StableDiffusion.
I have generated the text embeddings using `emb = StableDiffusion.get_text_embeds("prompt")`, and generate an image which is of shape `[1,3,256,256]`. I then pass both of these to `StableDiffusion.train_step(emb, img)`, with the rest of the parameters as their defaults. On the main branch I get an error that there is a shape mismatch.

I was wondering if I am passing anything incorrectly, and whether or not this is able to accept batch sizes larger than 1?

![image](https://github.com/ashawkey/stable-dreamfusion/assets/7675847/87dd8fdc-b824-4fda-990b-fe7aff2e20e4)

I notice that before it is being passed into the unet, we repeat along the 0th dimension of the latents, but not of the text embedding, and doing that seems to fix it, but not sure if that's intended.

### Steps to Reproduce

See above.

I'm not calling this within StableDreamfusion, but externally.

### Expected Behavior

I expected this to just work, but not sure if I I need to change the batch size of the text embedding.

### Environment

CUDA 11.7, Python3.11.2

**Comment by JulianKnodt** [comment]
after more futzing around with it, I realize that it is required to pass both an unconditional text prompt, as well as a conditional, view-dependent prompt.

**Comment by kingnobro** [comment]
Very useful

**Comment by yitongdeng** [comment]
Tremendous! Helped a ton
