### ISSUE TITLE
Long inference times

### ISSUE THREAD

**Issue by jclarkk** [ashawkey/stable-dreamfusion#281]
### Description

Hey,

First of all, kudos for the amazing work on this project.

On text-to-3D using -O and --vram_O I'm getting inference times of 2 and a half hours. Does that sound reasonable?

### Steps to Reproduce

python3.10 main.py -O --text "dragon wings and unicorn head hybrid creature, highly detailed" --workspace output --vram_O

### Expected Behavior

Create a 3D asset within a reasonable time.

### Environment

Debian 10
CUDA 11.7
Python 3.10

Hardware
GCP a2-highgpu-1g
NVIDIA A100 40GB

**Comment by ashawkey** [comment]
@jclarkk Hi, for A100 this sounds too long. You may consider removing `--vram_O` as there are plenty of memory.

**Comment by jclarkk** [comment]
Removing the --vram_O and using 5000 iters has lowered the time to 50 minutes.

Thanks fo the response.
