### ISSUE TITLE
Case study: 2D->3D challenges

### ISSUE THREAD

**Issue by claforte** [ashawkey/stable-dreamfusion#294]
UPDATE: my team has migrated to ThreeStudio where we just ran similar experiments, after much optimization. https://github.com/threestudio-project/threestudio/pull/166

In https://github.com/ashawkey/stable-dreamfusion/pull/293 I added new challenges for 2D->3D. I'll track here some of the early results and progress.

Initial conclusions:
- the estimated depth and normals are often wrong and result in severe errors that are unrecoverable in later phases, even when using an outrageously high number of denoising iterations.

# baby_pheonix_on_ice

![baby_phoenix_on_ice](https://github.com/ashawkey/stable-dreamfusion/assets/5090329/dd5ae24d-d22f-425e-8290-dfc25a986471)

## Results (end of phases1, 2, 3)

Result after phase 1 (zero123):

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/da8acc0b-4d8c-4c2b-a104-ff669480f80d

Phase 2:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/bd971c6f-5a71-4944-afcb-0ad5beff53d1

Phase 3:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/4a246392-9211-4bfc-99b6-8d5ae7937bc9

Conclusion: I suspect that the estimated depth and/or normals are wrong, and are keeping the reconstruction stuck in a local minimum. 

# beach_house_1

![beach_house_1](https://github.com/ashawkey/stable-dreamfusion/assets/5090329/940e5dc5-32c7-4f0e-b1ef-f9e491ba70c3)

The reconstruction failed early in phase 2.

Phase 1 result:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/4edbd7f0-bf3f-4b2b-bbfd-a828e00d628e

Phase 2 partial result:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/94f0d2b6-5751-411c-ae29-8fa37ca31cfd

# beach_house_2

![beach_house_2](https://github.com/ashawkey/stable-dreamfusion/assets/5090329/a021acba-06b9-4939-96dd-3ed6dcac4029)

The reconstruction failed early in phase 2.

Phase 1 result:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/58a2c6dd-1de8-44ce-af11-435fbff302c0

Phase 2 partial result:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/b995a289-62f6-4ed9-9b38-44dc68f68ccc

# bollywood_actress

![bollywood_actress](https://github.com/ashawkey/stable-dreamfusion/assets/5090329/3841acd3-fa6b-40fb-878e-33fc1bbeb30c)

Phase 1 result: WARNING: looks gruesome!

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/687ef521-d1c4-46ae-a72f-320cc424d5ef

Zero123 really struggles with this poor lady.. presumably because it's out of its training distribution...

Phase 2 result:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/3cc6dc0a-cd0b-4bbb-8265-af22cf7c311d

Phase 3 failed due to insufficient VRAM.

# church_ruins

![church_ruins](https://github.com/ashawkey/stable-dreamfusion/assets/5090329/d95b58c2-bba4-4ace-b682-2d948f0ff8ab)

Phase 1:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/2b30b9dc-1493-47b8-8ead-d8043128c7f0

The results of this phase look plausible, but have lots of holes.

Phase 2:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/3fa31f70-137d-42d8-a3ce-5feae5640dd6

Lots of concavities that don't look realistic.

# futuristic_car

![futuristic_car](https://github.com/ashawkey/stable-dreamfusion/assets/5090329/81920f96-54b3-410f-921e-b5902b6a5e6c)

Phase 1:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/802f4ec0-af04-4645-a428-7dc36600f8a9

Lots of big holes...

Phase 2:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/cdcb8bcf-e829-4951-a2a6-77addc4f5116

the depth of the car has shortened, the side and back are now completely unrecognizable.

# mona_lisa

![mona_lisa](https://github.com/ashawkey/stable-dreamfusion/assets/5090329/c2264ee2-6abd-4668-9a34-7ad8a95dd9df)

This is an extra-hard challenge, since the Monal Lisa is well-known to be flat.

Phase 1:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/0a9b1144-333d-4311-86d7-a2454cb760ec

A mirror image is in the back.

Phase 2:

https://github.com/ashawkey/stable-dreamfusion/assets/5090329/50b011af-6d3c-4288-9257-b35f95ddef5b

The nose has emerged but the back image remains.

Phase 3 wasn't run since Phase 2 was already problematic.

**Comment by claforte** [comment]
UPDATE: my team has migrated to ThreeStudio where we just ran similar experiments, after much optimization. https://github.com/threestudio-project/threestudio/pull/166. I will close this issue.

**Comment by kings-rgb** [comment]
Hi, how to achieve Phase2 and Phase3, could you share the corresponding code？
