### ISSUE TITLE
Question about Image normalization before VAE encoding

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [ashawkey/stable-dreamfusion#31]
Hi,

Thanks for the amazing work on open-sourcing dream-fusion. 

I just wanted to double-check this [line](https://github.com/ashawkey/stable-dreamfusion/blob/main/nerf/sd.py#L151)
```
imgs = 2 * imgs - 1 
```

Seems like an unusual normalization strategy but maybe I am wrong,

Thanks again !
Thibault

**Comment by ashawkey** [comment]
@ThibaultGROUEIX Hi, this seems to be the default transformation used in stable-diffusion, to convert image float range from [0, 1] into [-1, 1]. You can find it in the last part of [this tutorial](https://huggingface.co/blog/stable_diffusion).
