### ISSUE TITLE
some error about test

### ISSUE THREAD

**Issue by cwwjyh** [ashawkey/stable-dreamfusion#317]
### Description

I'm trying to run the examples from README: **CUDA_VISIBLE_DEVICES=0 python main.py -O --image data_1/output_scan105_rgba.png --workspace trial_image_dmtet_1 --dmtet --test  --save_mesh**, but any tries still results in the following error:
Should I load a checkpoint for this test?
![1686831891485](https://github.com/ashawkey/stable-dreamfusion/assets/26154160/e2cd3be6-638e-456d-840d-b83aa2720edb)
![1686831921537](https://github.com/ashawkey/stable-dreamfusion/assets/26154160/0c5ea12b-06f9-4023-a147-680568dd5420)

### Steps to Reproduce

run:  CUDA_VISIBLE_DEVICES=0 python main.py -O --image data_1/output_scan105_rgba.png --workspace trial_image_dmtet_1 --dmtet --test --save_mesh

### Expected Behavior

 test successfully

### Environment

ubuntu：20.04  CUDA：11.7， torch：2.0.1

**Comment by saullas** [comment]
Hey @cwwjyh, did you figure out what was the problem? I have the same issue

**Comment by cwwjyh** [comment]
> 

"--workspace xxx" , xxx should replace by your saved address. For example, I saved the result in **trial2_imagetext_scan65**, the xxx should replaced by **trial2_imagetext_scan65**
