### ISSUE TITLE
New zero123-XL released

### ISSUE THREAD

**Issue by stas-polukeev** [ashawkey/stable-dreamfusion#327]
Hi! The authors of zero123 just released a new version, zero123-XL, it could increase the quality of image-to-3D generation, if you use this in your repo. Here is the link: https://github.com/cvlab-columbia/zero123.

**Comment by ashawkey** [comment]
Thanks! I have updated the model link.

**Comment by johnwon2007** [comment]
doesn't the line in main.py need to be changed in order to use the new version zero123-xl.ckpt? or no
parser.add_argument('--zero123_ckpt', type=str, default='./pretrained/zero123/105000.ckpt', help="ckpt for zero123")

**Comment by johnwon2007** [comment]
doesn/t the line in main.py need to be changed in order to use the new zero-xl.ckpt? or no
around line 200
parser.add_argument('--zero123_ckpt', type=str, default='./pretrained/zero123/105000.ckpt', help="ckpt for zero123")

**Comment by ashawkey** [comment]
@johnwon2007 You are right! I have fixed this.

**Comment by HaoyangHuang** [comment]
how to test zero123 with the newest zero123-xl.ckpt? thanks...

**Comment by wangjksjtu** [comment]
@ashawkey @stas-polukeev  I am curious what is the license for zero123-xl, thanks a lot!

**Comment by stas-polukeev** [comment]
@wangjksjtu I would assume they are the same, because the only difference is the training data, but i could be wrong.
