### ISSUE TITLE
Acceleration with NerfAcc

### ISSUE THREAD

**Issue by AmanKishore** [ashawkey/stable-dreamfusion#33]
Curious if https://github.com/KAIR-BAIR/nerfacc could accelerate training and inference for dreamfusion!

**Comment by ashawkey** [comment]
@AmanKishore Hi, in fact we already use a similar acceleration technique (check torch-ngp) for the nerf part. The major time bottleneck is the diffusion model now.

**Comment by AmanKishore** [comment]
Oh that's great!

**Comment by thuanz123** [comment]
@ashawkey you might be interested in this https://twitter.com/realDanFu/status/1580641495991754752
