### ISSUE TITLE
Assertion Error Torch not compiled with Cuda

### ISSUE THREAD

**Issue by Ahmed-Raza-Khanzada** [ashawkey/stable-dreamfusion#342]
### Description

I am getting Assertion while preprocessing image cause I dont have Cuda, its not working without Cuda.

### Steps to Reproduce

python preprocess_image.py hdshirt.png

### Expected Behavior

hdshirt_rgba.png image should be generated

### Environment

windows 11,python 3.7

**Comment by Justinfungi** [comment]
You need to reinstall PyTorch with GPU support. The installation of Pytorch is wrong so you pytorch couldn't run with CUDA

**Comment by Ahmed-Raza-Khanzada** [comment]
yeah its working fine now but its not generating clothes mesh perfectly ,I am getting good results on other objects but not on clothes even I have segmented the clothes my self and then feed the segmented clothes(shirt,pant) to this model to get the better results even though being know that its segment object itself but not getting good results on clothes maybe because its trained on general dataset thats why,By the way superb work.
