### ISSUE TITLE
--save_mesh not saving mesh and --gui only showing empty scene

### ISSUE THREAD

**Issue by MondRubberduck** [ashawkey/stable-dreamfusion#35]
Hey, Whenever I run a prompt, it gives me the correct pngs and mp4 of a model rotating and all of that, but I cannot save the mesh. It´s not saving any obj and the GUI prompt only shows an empty scene. I tried the suggestions with increasing the albedo_iterations and all but... still no mesh. Any ideas?
Windows 11, Python 3.9.13, NVidia RTX A6000

**Comment by ashawkey** [comment]
@MondRubberduck So the video shows a correctly generated object, and only the mesh exporting fails? Could you check the printed log? It should say something like this:
```
==> Saving mesh to trial/mesh
[INFO] running xatlas to unwrap UVs for mesh: v=(129072, 3) f=(257500, 3)
[INFO] writing obj mesh to trial/mesh/mesh.obj
[INFO] writing vertices (129072, 3)
[INFO] writing vertices texture coords (236023, 2)
[INFO] writing faces (257500, 3)
==> Finished saving mesh.
```

**Comment by MondRubberduck** [comment]
@ashawkey !Thank you for the reply! It actually doesn´t 

`[INFO] Trainer: df | 2022-10-11_11-16-57 | cuda | fp16 | trial
[INFO] #parameters: 12249015
[INFO] Loading latest checkpoint ...
[WARN] No checkpoint found, model randomly initialized.
==> Start Test, save results to trial\results
 97% 97/100 [00:03<00:00, 53.96it/s]==> Finished Test.
==> Saving mesh to trial\mesh
[INFO] running xatlas to unwrap UVs for mesh: v=(0, 3) f=(0, 3)
100% 100/100 [00:04<00:00, 20.19it/s]
Traceback (most recent call last):`

Then it goes through some files and the last bit:
`RuntimeError: instance mode - pos must have shape [>0, >0, 4]`

It warns me that there are no checkpoints. However, I do have my checkpoints in the default files structure _./stable-dreamfusion/mytest/checkpoints_

Couple of large PTH files.  -> df_ep0100.pth (for example)

**Comment by MondRubberduck** [comment]
Update: I literally didn´t change anything. Deleted all the checkpoints /results/df´s etc and ran another test with:

`python main.py --text "a high quality, detailed photo of a mercedes benz" --workspace mytest -O --iters 5000 --albedo_iters 6000 --lambda_entropy 1e-5`

Looks like shit (well duh. These settings were for a quick result), but at least I got a mesh from it.

**Comment by MondRubberduck** [comment]
@ashawkey If I may steal your time for one more second: What parameters have the biggest impact on quality? Thanks
