### ISSUE TITLE
Segmentation fault (core dumped) when running xatlas to unwrap UVs 

### ISSUE THREAD

**Issue by alanyannick** [ashawkey/stable-dreamfusion#36]
Hey, Thanks for the nice repo :)
 
The training process works well on Python 3.9:
```
==> Start Test, save results to mytest/results
100% 100/100 [00:11<00:00,  8.40it/s]==> Finished Test.
100% 100/100 [00:13<00:00,  7.52it/s]
==> Saving mesh to mytest/mesh
[INFO] running xatlas to unwrap UVs for mesh: v=(126658, 3) f=(252036, 3)
Segmentation fault (core dumped)
```
but I met a issue when I was trying to do the test exp, which I can't get anything by using the xatlas to unwrap mesh. 
The xatlas will crush for some unknown reason **_(Segmentation fault (core dumped))_**. To be more specfic, I find that it will crush on the Line 195-197 of the nerf/renderer.py; 
```
            rast, _ = dr.rasterize(glctx, uv.unsqueeze(0), ft, (h, w)) # [1, h, w, 4]
            xyzs, _ = dr.interpolate(v.unsqueeze(0), rast, f) # [1, h, w, 3]
            mask, _ = dr.interpolate(torch.ones_like(v[:, :1]).unsqueeze(0), rast, f) # [1, h, w, 1]
```

I also try to solve it by changing the version of scikit-learn, cuda, torch, but all of them still can't solve that; Do you have any ideas? Thanks!

**Comment by ashawkey** [comment]
@alanyannick you could first try the examples provided by [xatlas](https://github.com/mworchel/xatlas-python). I doubt about the version of OS.

**Comment by alanyannick** [comment]
Thanks, the examples can pass through, but still get crush :( 
Just wondering what kind of python version ur using (e.g. 3.7.12 or 3.9.12?) and the corresponding version of xatlas package (by pip install xatlas or install locally from source [xatlas](https://github.com/mworchel/xatlas-python) )?

**Comment by alanyannick** [comment]
I've solved it with some special configs. Thanks for the repo.

**Comment by xibi777** [comment]
Hello, thanks for the kind comments. I met the same issue,  could you please share the solution to the problem?
