### ISSUE TITLE
The .obj model cannot show texture 

### ISSUE THREAD

**Issue by xwenyafeng** [ashawkey/stable-dreamfusion#44]
Hi, dear author, thanks for you awesome work!

I follow the usage and run "python main.py --text "a hamburger" --workspace trial -O"
after the training is finished run "python main.py --workspace trial -O --test --save_mesh" in order to get the textured mesh.

The .obj .png .mtl files was successful saved. But I open the .obj in blender, it only show the mesh below(no texture on it) 

The shape of the mesh looks correct, the .png .mtl both correct, the results of depth.mp4 and rgb.mp4 are correct. 

**_The only problem is the mesh don't have texture. I test on local and colab, same result. Did I miss something?  Thank you!_**
![image](https://user-images.githubusercontent.com/90488570/196324078-1e63ac60-9168-40dc-8228-e1507da04060.png)

**Comment by ashawkey** [comment]
@xwenyafeng Guess you should choose to display materials (top right corner in the editor) in blender?

**Comment by xwenyafeng** [comment]
> @xwenyafeng Guess you should choose to display materials (top right corner in the editor) in blender?

You are right. It looks like the mesh have too many faces, blender did not load the texture automatically. Thanks
