### ISSUE TITLE
SDS loss

### ISSUE THREAD

**Issue by roibaron** [ashawkey/stable-dreamfusion#45]
According to section 2 in the paper, `epshat =  pred_noise_text + guidance_scale * (pred_noise_text - pred_noise_uncond)`.
While it seems that in the implementation in [sd.py](https://github.com/ashawkey/stable-dreamfusion/blob/main/nerf/sd.py#L95), it's assigned as: `epshat =  pred_noise_uncond + guidance_scale * (pred_noise_text - pred_noise_uncond)`.
Is this intentional?

**Comment by ashawkey** [comment]
@roibaron Hi, you may check [this](https://github.com/ashawkey/stable-dreamfusion/issues/32). Since the guidance_scale is set to a very large value, this change of order may not have a siginificant influence.
