### ISSUE TITLE
Where can I get the file diffusion_pytorch_model.bin?  can I use the downloaded stable-diffusion-v1-4.ckpt model?

### ISSUE THREAD

**Issue by huanheaha** [ashawkey/stable-dreamfusion#46]
Can the downloaded sd-v1-4.ckpt model be put in which folder to use directly?

**Comment by ashawkey** [comment]
The easiest way is to use the weights provided by the `diffuser` library, you could check the readme and colab examples.

**Comment by huanheaha** [comment]
> @huanheaha The easiest way is to use the weights provided by the `diffuser` library, you could check the readme and colab examples.

![image](https://user-images.githubusercontent.com/52036078/196910469-b891d741-bd7a-4c63-b8ef-d6ab3a5ea701.png)
it told me " no file named diffusion_pytorch_model.bin found in directory CompVis/stable-diffusion-v1-4"，so i don't know how to get this file.
