### ISSUE TITLE
no module named cv2

### ISSUE THREAD

**Issue by Krasnomakov** [ashawkey/stable-dreamfusion#48]
Tried to install and run on mac and linux Ubuntu, both give this problem. 
<img width="735" alt="Screenshot 2022-10-21 at 11 51 02" src="https://user-images.githubusercontent.com/104280018/197167750-d9851ecc-3717-417b-a087-024cc1cc5b2c.png">

**Comment by ashawkey** [comment]
@Krasnomakov Hi, please follow the readme to install the required dependencies.
