### ISSUE TITLE
save mesh does not work

### ISSUE THREAD

**Issue by flobotics** [ashawkey/stable-dreamfusion#52]
hi,
i pulled the latest and when i click save mesh in the GUI it responds on powershell

stable-dreamfusion\nerf\gui.py", line 254, in callback_mesh
    self.trainer.save_mesh(resolution=256, threshold=10)
TypeError: save_mesh() got an unexpected keyword argument 'threshold'

When i delete the threshold=10 in this func call, it runs and saves a mesh

**Comment by ashawkey** [comment]
Thanks!
