### ISSUE TITLE
Colab for Artists/Game Devs

### ISSUE THREAD

**Issue by Delta-Ark** [ashawkey/stable-dreamfusion#6]
Hi There,

Would you be open to making a colab for artists/game devs that also allows you to save the model as a mesh or ply. Here is a similar colab for dreamfields: https://github.com/shengyu-meng/dreamfields-3D . I've been working with it to move the meshes into the game engine, see here https://www.instagram.com/p/CjURPkWrMvh/ and here https://www.instagram.com/p/CjUZS2zuvRS/

**Comment by lalalune** [comment]
Looks like there is one here now:
https://colab.research.google.com/drive/1UAjdFenAqSPEBAocpjm5Lyr7J1I69kb2?usp=sharing
However, other user is getting black input: https://github.com/ashawkey/stable-dreamfusion/issues/6

**Comment by lalalune** [comment]
Here, I fixed it (removed --test)
https://colab.research.google.com/drive/1bLfrfbW8vDs2UqcIYtXi7a3wHyPzhSc5?usp=sharing

**Comment by ashawkey** [comment]
Hi, thanks for the advice! I'm preparing a colab now.

**Comment by ashawkey** [comment]
welcome to try!
https://colab.research.google.com/drive/1MXT3yfOFvO0ooKEfiUUvTKwUkrrlCHpF?usp=sharing
