### ISSUE TITLE
SDS Loss Question - RGB Optimization

### ISSUE THREAD

**Issue by jakericedesigns** [ashawkey/stable-dreamfusion#66]
Howdy! :) 
I was curious if it was possible to just do RGB optimization of a 2d texture using the SDS loss described in this repo? I've been attempting to do that for the past few hours, with little success, which leads me to believe that I'm misunderstanding how the SDS stuff actually works... My understanding is that given some rendered image, optimizing with the SDS loss will attempt to adjust the input radiance field such that when re-rendered and re-encoded, the new latent encoding more matches the input text encoding? 

I'm curious if anyone has any input regarding this, since I think it would be really useful for optimizing textures on 3d polygonal models! 

I'd be more than happy to share my working file regarding this, however it's pretty much what you expect. im just shoving an rgb tensor into the train_step function repeatedly and praying to a higher power that it optimizes into something coherent (it doesn't).

**Comment by jakericedesigns** [comment]
Update: SDS loss does actually work for arbitrary RGB textures (I was just being a noob). If your goal is to optimize textures on 3d models, make sure that the entire screen is filled by the model or close to it. Otherwise the optimizer spins its gears trying to optimize the backdrop (which it can't), and ultimately nothing coherent comes out.

But assuming you play your cards right something comes out! not sure why the colors are so scuffed, but that's a problem for another day. The prompt for this test was "artstation rock texture"

![image](https://user-images.githubusercontent.com/32991444/198944000-c0ac75e7-a7e1-4404-8104-92b9022a5b2b.png)

**Comment by Quantuman134** [comment]
Hi,
I have also used SDS to update a 2D image from noise, and I think it should work out in the 2D condition right? The fact is that I obtained the images and could recognized them were consistent with my text prompts. However, all these images appeared structure-like noise. And I think this noise is similar to what you have displayed. Do you have any progress on this 2D generation?

several obtained images are as following:
![test_3](https://github.com/ashawkey/stable-dreamfusion/assets/68807149/405f1e03-40fe-4ead-8401-0335839d817b)


![ep_1000_3](https://github.com/ashawkey/stable-dreamfusion/assets/68807149/913b7daf-d43b-454d-aad5-7b78b17e86ee)

**Comment by yuanzhi-zhu** [comment]
Hi @Quantuman134, is your image in rgb or latent space? Your results seems to be normal for optimising rgb image with sds

**Comment by Quantuman134** [comment]
Hi @yuanzhi-zhu, thanks for your reply! Yes, my image is in rgb space. I have just seen the similar results in other issues, and known the optimization in latent space would obtain cleaner results. The link of issue is this: 
https://github.com/ashawkey/stable-dreamfusion/issues/96#issue-1463918301
I also tried their example, the result was clean. However, a new problem raised, the image seemed to be too smooth and flat.
![tmp_lat_img_600](https://github.com/ashawkey/stable-dreamfusion/assets/68807149/bffdf30a-96f7-46c0-9a2b-27f944060c02)

**Comment by yuanzhi-zhu** [comment]
Hi @Quantuman134 ,
I guess you are using a smaller cfg?
These images, to me at least, reach the limit of SDS loss.

Recently, the vsd loss proposed in https://arxiv.org/abs/2305.16213 addressed this issue.

And I have a 2d unofficial implementation of prolific dreamer here https://github.com/yuanzhi-zhu/prolific_dreamer2d. Please feel free to try it out ;)

**Comment by Quantuman134** [comment]
Hi @yuanzhi-zhu, 
Yes, I forgot to use the large weight. Even though using a large cfg weight, as you say, the result approach the limit of SDS.

I have read the paper about vsd, and also found your demo just a few minutes ago XD.

Thanks for your advice and I will try your demo and the VSD later. Whatever the noise artifact seems to be solved temporarily. And I can go on my work using the diffusion model. Thank you again!
