### ISSUE TITLE
loss nan and empty output

### ISSUE THREAD

**Issue by zzysay** [ashawkey/stable-dreamfusion#68]
Thank you for your kindness to open source!

I'm trying to reproduce the project, but the training process seems to be unstable, and the loss value is always 0.0000(nan).

Besides, even though I trained 100,000 iterations, the model still has no valid output (completely black scene).

Looking forward to your quick reply...

**Comment by smearle** [comment]
Have you tried running without `--cuda_ray` (this is turned on by `-O` as well). While playing with the NeRF I noticed this option seems to result in strange output. Just a guess though. Maybe also give CLIP guidance a shot?

**Comment by zzysay** [comment]
I reconfigure my environment (mainly upgrading cuda from 10 to 11), and then run the project again. It seems to work. After enough training, some meaningful images can be produced ...
