### ISSUE TITLE
Colab not working

### ISSUE THREAD

**Issue by aliabid94** [ashawkey/stable-dreamfusion#7]
https://colab.research.google.com/drive/1UAjdFenAqSPEBAocpjm5Lyr7J1I69kb2?usp=sharing is not working. Produces a black video and empty noise as the outputs when "Run All".

**Comment by lalalune** [comment]
You are calling
! python main_nerf.py --text "a cat" --workspace trial -O --test
Remove `--test` to get more iterations and a working model :)

**Comment by ashawkey** [comment]
welcome to try!
https://colab.research.google.com/drive/1MXT3yfOFvO0ooKEfiUUvTKwUkrrlCHpF?usp=sharing

**Comment by aliabid94** [comment]
thanks will try!
