### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr/lib/cuda'

### ISSUE THREAD

**Issue by gianluigidalessandro** [ashawkey/stable-dreamfusion#77]
Hello, not sure if some of you has had the same problem while installing the code.

When I try to run:
bash scripts/install_ext.sh
or
pip install ./raymarching

I get the error:
No CUDA runtime is found, using CUDA_HOME='/usr/lib/cuda'

I have Ubuntu 22 jammy jellyfish, pytorch 1.13 and cuda 1.15.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
If u solved this issue. can u please mention how?
The error I get is :
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-12.1'

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
> Hello, not sure if some of you has had the same problem while installing the code.
> 
> When I try to run: bash scripts/install_ext.sh or pip install ./raymarching
> 
> I get the error: No CUDA runtime is found, using CUDA_HOME='/usr/lib/cuda'
> 
> I have Ubuntu 22 jammy jellyfish, pytorch 1.13 and cuda 1.15.

If u solved this issue. can u please mention how?
The error I get is :
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-12.1'

**Comment by polinaverzun** [comment]
Processing ./raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching
  Building wheel for raymarching (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      running bdist_wheel
      running build
      running build_ext
      error: [Errno 13] Permission denied: '/usr/local/cuda/bin/nvcc'
      [end of output]
