### ISSUE TITLE
DreamFusion

### ISSUE THREAD

**Issue by Shikamaru5** [ashawkey/stable-dreamfusion#80]
This is less of an issue and more of a timesaver for me but if one wanted to swap StableDiffusion for Imagen, any advice on the easiest way to accomplish that?

**Comment by ashawkey** [comment]
@Shikamaru5 Hi, since imagen is not publicly available, I don't think there is a way to accomplish it...

**Comment by Shikamaru5** [comment]
Is that more of a copyright thing? I was just asking because there is an Imagen proxy on github that can be trained and was wondering the best way if I were to go in that direction. https://github.com/lucidrains/imagen-pytorch
