### ISSUE TITLE
raymmarching and cuda not available even if i have them both installed.

### ISSUE THREAD

**Issue by DuckersMcQuack** [ashawkey/stable-dreamfusion#86]
Edit. Cuda and raymarching both fails, was supposed to be topic header. Sorry about that.

(base) C:\stable-dreamfusion-main\stable-dreamfusion-main>pip install ./raymarching
Processing c:\stable-dreamfusion-main\stable-dreamfusion-main\raymarching
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\stable-dreamfusion-main\stable-dreamfusion-main\raymarching\setup.py", line 29, in <module>
          raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
      RuntimeError: Could not locate a supported Microsoft Visual C++ installation
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

________________________________________

(base) C:\stable-dreamfusion-main\stable-dreamfusion-main>python main.py --text "a hamburger" --workspace trial -O
C:\Users\Duckers\AppData\Roaming\Python\Python39\site-packages\torch\amp\autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Traceback (most recent call last):
  File "C:\stable-dreamfusion-main\stable-dreamfusion-main\raymarching\raymarching.py", line 10, in <module>
    import _raymarching as _backend
ModuleNotFoundError: No module named '_raymarching'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-dreamfusion-main\stable-dreamfusion-main\main.py", line 95, in <module>
    from nerf.network_grid import NeRFNetwork
  File "C:\stable-dreamfusion-main\stable-dreamfusion-main\nerf\network_grid.py", line 6, in <module>
    from .renderer import NeRFRenderer
  File "C:\stable-dreamfusion-main\stable-dreamfusion-main\nerf\renderer.py", line 12, in <module>
    import raymarching
  File "C:\stable-dreamfusion-main\stable-dreamfusion-main\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "C:\stable-dreamfusion-main\stable-dreamfusion-main\raymarching\raymarching.py", line 12, in <module>
    from .backend import _backend
  File "C:\stable-dreamfusion-main\stable-dreamfusion-main\raymarching\backend.py", line 28, in <module>
    raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
RuntimeError: Could not locate a supported Microsoft Visual C++ installation

(base) C:\stable-dreamfusion-main\stable-dreamfusion-main>

**Comment by ashawkey** [comment]
Hi, please check the latest pure-pytorch version if the CUDA extensions fail to install.

**Comment by DuckersMcQuack** [comment]
https://pastebin.com/wvu1Uspp tried the very latest now. And pretty much everything by the looks of it conflicts and requests an earlier version of quite a lot. Any idea what to do in this situation? Pretty new to anaconda and this stuff, so no idea what to do from here.

**Comment by DuckersMcQuack** [comment]
got one step closer! Installed nvidia cuda toolkit from nvidia, vsbuild tools, and error above is fixed so far Now there's these

 × Running setup.py install for freqencoder did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v11.8'
      running install
      C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      Traceback (most recent call last):
