### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by SpicyMelonYT** [ashawkey/stable-dreamfusion#88]
TypeError: forward() takes 2 positional arguments but 4 were given

![image](https://user-images.githubusercontent.com/80491863/202285593-346b478e-0aaf-49f8-a697-e6f2e3ff260d.png)

**Comment by ashawkey** [comment]
Hi, please check the latest pure-pytorch version if the CUDA extensions fail to install.
