### ISSUE TITLE
Minimum vram required

### ISSUE THREAD

**Issue by matehun00** [ashawkey/stable-dreamfusion#89]
It's not really an issue, it's just a question.
Like whats the bare minimum it would run with.

**Comment by ashawkey** [comment]
@matehun00 Hi, for GPU the default setting requires at least 15GB, but I guess it could be reduced by changing some settings. You can refer to the `main.py` for the configs.

**Comment by matehun00** [comment]
To be more specific, like would it be posibble with a rtx 3060 12gb?

**Comment by ashawkey** [comment]
@matehun00 You'll have to try it yourself.
