### ISSUE TITLE
Problem in computing normals

### ISSUE THREAD

**Issue by aryanmikaeili** [ashawkey/stable-dreamfusion#97]
Hello and thanks for awesome re-implementation

In the function `finite_difference_normal` when computing densities of perturbed points there is clamping to [-bound, +bound] for example in this line: `self.common_forward((x + torch.tensor([[epsilon, 0.00, 0.00]], device=x.device)).clamp(-self.bound, self.bound))`.

In the referenced work because the output of the model are sdfs it makes sense that the values be bounded. However here because the outputs of the density model are densities which can have any value in the range [0, infinity], clamping it is wrong and results in wrong normals. Fixing this might fix the issues with normal-based losses.

**Comment by ashawkey** [comment]
@aryanmikaeili Hi, I think we are clamping the coordinates (i.e., `x + epsilon`), instead of clamping the density value after forwarding?
